apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: simpleapp
  namespace: default
spec:
  serviceAccountName: kapp-app-simpleapp
  fetch:
  - git:
      url: https://github.com/clastix/src-to-oci-source
      ref: origin/main
  - git:
      url: https://github.com/clastix/src-to-oci-build
      ref: origin/main
  - git:
      url: https://github.com/clastix/src-to-oci-deploy
      ref: origin/test
  template:
  - ytt:
      paths:
      - "./1"
      - "./2"
  - kbld:
      paths:
      - "-"
  deploy:
  - kapp: {}
