apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: go-simpleapp
  namespace: default
spec:
  serviceAccountName: kapp-app-simpleapp
  fetch:
  - git:
      url: https://github.com/clastix/src-to-oci-go-simpleapp
      ref: origin/main
  - git:
      url: https://github.com/clastix/src-to-oci-build
      ref: origin/feat/language_version
  - git:
      url: https://github.com/clastix/src-to-oci-deploy
      ref: origin/main
  template:
  - ytt:
      paths:
      - "./1"
      - "./2"
      inline:
        paths:
          values2.yml: |-
            #@data/values
            ---
            app_name: go-simpleapp
            programming_language_runtime: go
            programming_language_runtime_version: "1.16.10"
            push_images_repo: quay.io/maxgio92/go-simpleapp
            replicas: 1
  - kbld: {}
  deploy:
  - kapp: {}
