apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: nodejs-simpleapp
  namespace: default
spec:
  serviceAccountName: kapp-app-simpleapp
  fetch:
  - git:
      url: https://github.com/clastix/src-to-oci-nodejs-simpleapp
      ref: origin/main
  - git:
      url: https://github.com/clastix/src-to-oci-build
      ref: origin/main
  - git:
      url: https://github.com/clastix/src-to-oci-deploy
      ref: origin/main
  template:
  - ytt:
      paths:
      - "./1"
      - "./2"
      inline:
        paths:
          values2.yml: |-
            #@data/values
            ---
            app_name: nodejs-simpleapp
            programming_language_runtime: nodejs
            push_images_repo: quay.io/maxgio92/nodejs-simpleapp
            replicas: 1
            expose_svc: "true"
  - kbld: {}
  deploy:
  - kapp: {}
