apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: kapp-controller-kubectl-buildkit
  namespace: kapp-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubectl-buildkit
subjects:
- kind: ServiceAccount
  name: kapp-controller-sa
  namespace: kapp-controller

